trigger beforeOpportunityTrigger on Opportunity (before update) {
    for (Opportunity o : Trigger.new){        
        
        if(o.Org_Vta__c=='COL-ZP' || o.Org_Vta__c=='MEX-ZP' || o.Org_Vta__c=='ARG-ZP'){
            
            List<OpportunityLineItem> lines = [SELECT id_tool__c, TotalPrice, Cantidad__c FROM OpportunityLineItem where OpportunityId=:o.Id];
            
            o.total_acuerdo__c = 0;
            
            if(o.autogenerated__c == false){
                if(o.Tipo_Facturacion__c == 'Periodica' && o.from_api__c == false){
                    for(OpportunityLineItem oli: lines) {
                        if(oli.Cantidad__c==null){ 
                            oli.Cantidad__c=1; 
                        }
                        o.total_acuerdo__c += oli.TotalPrice * oli.Cantidad__c;
                        
                    }
                    
                }else{
                    o.total_acuerdo__c = o.importe_final__c;
                }
           }
            
        }
    }
}