trigger OppGenerateFutureOP on Opportunity (after insert, after update) {
    for (Opportunity opp : Trigger.new){
        
        if(opp.StageName == 'Cerrada ganada - Aprobada' && opp.autogenerated__c==false &&
        (opp.Org_Vta__c=='MEX-ZP' || opp.Org_Vta__c=='COL-ZP' || opp.Org_Vta__c=='ARG-ZP') && opp.Cantidad_Facturas__c != '1' && opp.Numero_Factura__c==1){
            
         ZPGenerateFutureOpp.createMensualOpportunity(opp.Id);       
        
        }
    }
}