trigger OppSendSale on Opportunity (after insert, after update) {
    if(!System.isFuture()){
        for (Opportunity opp : Trigger.new)
        {
            Account a = [SELECT Negocio__c, Country__c  from Account where Id=:opp.AccountId];
            if(opp.Probability==100){
                 OpportunityLineItem[] olis = [SELECT Id, Opportunity.Org_Vta__c, Discount, Cantidad__c, PricebookEntry.Product2.Precio_editable__c, Tipo_Facturacion__c from OpportunityLineItem where OpportunityId =:opp.Id];
        
                 if(olis.size() > 0){              
                     for (OpportunityLineItem oli : olis){
                             for (OpportunityLineItem oli2 : olis){
                                 if(oli.Opportunity.Org_Vta__c != 'ARG-ZJ' && oli.PricebookEntry.Product2.Precio_editable__c == false && oli2.PricebookEntry.Product2.Precio_editable__c == false && oli2.Discount!=oli.Discount){
                                    opp.addError('No es posible asignar diferentes descuentos sobre la misma oportunidad');
                                 }
                             }
                             if(a.Negocio__c=='ZP' && (opp.Org_Vta__c =='MEX-ZP' || opp.Org_Vta__c =='COL-ZP' || opp.Org_Vta__c =='ARG-ZP') && opp.from_api__c==false && opp.Tipo_Facturacion__c != oli.Tipo_Facturacion__c){
                                 opp.addError('El Tipo de Facturacion de todos los productos debe ser el elegido en la Oportunidad'); 
                             }
                             if(a.Negocio__c=='ZP' && opp.autogenerated__c==false && opp.Tipo_Facturacion__c=='Periodica' && Integer.valueOf(opp.Cantidad_Facturas__c) != oli.Cantidad__c){
                                    opp.addError('La cantidad del acuerdo del producto debe coincidir con la cantidad de Facturas de la Oportunidad');
                             }
                     }
                 }
            }         
            
            if(opp.Probability==100 && opp.Aprobada__c==true && a.Negocio__c=='DM' && opp.from_api__c==false && opp.Estado_Envio__c=='Pendiente Envio'){  
               System.debug(LoggingLevel.INFO, 'Entra trigger OppSendSale');  
               
               // Valido que la fecha de inicio de los productos no sea menor que la fecha de envio (activacion del producto) 
               List<OpportunityLineItem> sales = [SELECT fecha_inicio_servicio__c, PricebookEntry.Product2.Family 
                                                        FROM OpportunityLineItem where OpportunityId=:opp.Id]; 
                                                        
               for(OpportunityLineItem oli: sales) {
                   
                   if(oli.PricebookEntry.Product2.Family == 'Pack Publicaciones' || oli.PricebookEntry.Product2.Family == 'Pack Listados'){
                       if(oli.fecha_inicio_servicio__c < System.today()){
                           oli.fecha_inicio_servicio__c = System.today();
                           update oli;
                       }
                   }     
                }
               
               // Envio contratacion
               DMContratacionCallOut.sendContratacion(opp.Id);
            }
            
        }
    }
}